### ISSUE TITLE
请问具体怎么添加下载的模型？除了放到model文件夹还需要修改那些文件？

### ISSUE THREAD

**Issue by YuehWenn** [terwer/siyuan-plugin-kanban-girl#5]
模型地址
https://mx.paul.ren/model/kurumi.html

**Comment by terwer** [comment]
放到模型位置之后，重启就行了。如果支持的话，换装就能用 
![image](https://github.com/terwer/siyuan-plugin-kanban-girl/assets/3259282/3e36b3b9-b2a6-438a-b8f5-cb803be354d7)
